[project]
name = "roar-net-code-fest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=8.4.2",
    "pytest-repeat>=0.9.4",
    "roar-net-api>=0.1.1",
    "tabulate>=0.9.0",
]
